<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- Copy .env only if it exists (for local development) -->
    <None Update=".env" Condition="Exists('.env')">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup Label="Shared References">
    <ProjectReference Include="..\..\Shared\Snippet.Shared\Snippet.Shared.csproj" />
  </ItemGroup>

  <!-- Assuming Central Package Management -->
  <ItemGroup Label="NuGet Package References">
    <PackageReference Include="Shared.Abstractions" />
    <PackageReference Include="Shared.Infrastructure" />
    <PackageReference Include="Shared.Users.Domain" />
    <PackageReference Include="Shared.Users.Application" />
    <PackageReference Include="Shared.Users.Infrastructure" />
    <PackageReference Include="Shared.Infrastructure.Generators" />
  </ItemGroup>

  <ItemGroup Label="Local Module References">
    <ProjectReference Include="..\..\Modules\Snippets\Snippet.Modules.Snippets.Application\Snippet.Modules.Snippets.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Snippets\Snippet.Modules.Snippets.Infrastructure\Snippet.Modules.Snippets.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup Label="Package References">
    <PackageReference Include="DotNetEnv" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <!-- PrivateAssets="all" ensures this dev-tool doesn't end up in the production container -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>


  <Target Name="GenerateEnvFile" AfterTargets="Build" Condition="'$(Configuration)' == 'Debug'">
    <Exec Command="dotnet tool run shared env generate -p $(MSBuildProjectDirectory) -o $(MSBuildProjectDirectory)\.env.example -c $(Configuration) -f" />
  </Target>

</Project>