/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Snippet.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../axios-instance';
import type { CollectionDto, CreateCollectionCommand, Error, UpdateCollectionCommand } from '../models';

export const createCollection = (createCollectionCommand: CreateCollectionCommand, signal?: AbortSignal) => {
  return customInstance<string>({
    url: `/api/collections`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createCollectionCommand,
    signal
  });
};

export const getCreateCollectionMutationOptions = <TError = Error[], TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCollection>>,
    TError,
    { data: CreateCollectionCommand },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCollection>>,
  TError,
  { data: CreateCollectionCommand },
  TContext
> => {
  const mutationKey = ['createCollection'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCollection>>,
    { data: CreateCollectionCommand }
  > = (props) => {
    const { data } = props ?? {};

    return createCollection(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCollectionMutationResult = NonNullable<Awaited<ReturnType<typeof createCollection>>>;
export type CreateCollectionMutationBody = CreateCollectionCommand;
export type CreateCollectionMutationError = Error[];

export const useCreateCollection = <TError = Error[], TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCollection>>,
      TError,
      { data: CreateCollectionCommand },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createCollection>>,
  TError,
  { data: CreateCollectionCommand },
  TContext
> => {
  const mutationOptions = getCreateCollectionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getUserCollections = (signal?: AbortSignal) => {
  return customInstance<CollectionDto[]>({ url: `/api/collections`, method: 'GET', signal });
};

export const getGetUserCollectionsQueryKey = () => {
  return [`/api/collections`] as const;
};

export const getGetUserCollectionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserCollections>>,
  TError = Error[]
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCollections>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserCollectionsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserCollections>>> = ({ signal }) =>
    getUserCollections(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserCollections>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserCollectionsQueryResult = NonNullable<Awaited<ReturnType<typeof getUserCollections>>>;
export type GetUserCollectionsQueryError = Error[];

export function useGetUserCollections<TData = Awaited<ReturnType<typeof getUserCollections>>, TError = Error[]>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCollections>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserCollections>>,
          TError,
          Awaited<ReturnType<typeof getUserCollections>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserCollections<TData = Awaited<ReturnType<typeof getUserCollections>>, TError = Error[]>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCollections>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserCollections>>,
          TError,
          Awaited<ReturnType<typeof getUserCollections>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserCollections<TData = Awaited<ReturnType<typeof getUserCollections>>, TError = Error[]>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCollections>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetUserCollections<TData = Awaited<ReturnType<typeof getUserCollections>>, TError = Error[]>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserCollections>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetUserCollectionsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getCollectionById = (id: string, signal?: AbortSignal) => {
  return customInstance<CollectionDto>({ url: `/api/collections/${id}`, method: 'GET', signal });
};

export const getGetCollectionByIdQueryKey = (id?: string) => {
  return [`/api/collections/${id}`] as const;
};

export const getGetCollectionByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getCollectionById>>,
  TError = Error[]
>(
  id: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCollectionById>>, TError, TData>> }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCollectionByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCollectionById>>> = ({ signal }) =>
    getCollectionById(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCollectionById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCollectionByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getCollectionById>>>;
export type GetCollectionByIdQueryError = Error[];

export function useGetCollectionById<TData = Awaited<ReturnType<typeof getCollectionById>>, TError = Error[]>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCollectionById>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCollectionById>>,
          TError,
          Awaited<ReturnType<typeof getCollectionById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCollectionById<TData = Awaited<ReturnType<typeof getCollectionById>>, TError = Error[]>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCollectionById>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCollectionById>>,
          TError,
          Awaited<ReturnType<typeof getCollectionById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCollectionById<TData = Awaited<ReturnType<typeof getCollectionById>>, TError = Error[]>(
  id: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCollectionById>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetCollectionById<TData = Awaited<ReturnType<typeof getCollectionById>>, TError = Error[]>(
  id: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCollectionById>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCollectionByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const updateCollection = (id: string, updateCollectionCommand: UpdateCollectionCommand) => {
  return customInstance<void>({
    url: `/api/collections/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateCollectionCommand
  });
};

export const getUpdateCollectionMutationOptions = <TError = Error[], TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCollection>>,
    TError,
    { id: string; data: UpdateCollectionCommand },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCollection>>,
  TError,
  { id: string; data: UpdateCollectionCommand },
  TContext
> => {
  const mutationKey = ['updateCollection'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCollection>>,
    { id: string; data: UpdateCollectionCommand }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateCollection(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCollectionMutationResult = NonNullable<Awaited<ReturnType<typeof updateCollection>>>;
export type UpdateCollectionMutationBody = UpdateCollectionCommand;
export type UpdateCollectionMutationError = Error[];

export const useUpdateCollection = <TError = Error[], TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCollection>>,
      TError,
      { id: string; data: UpdateCollectionCommand },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateCollection>>,
  TError,
  { id: string; data: UpdateCollectionCommand },
  TContext
> => {
  const mutationOptions = getUpdateCollectionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteCollection = (id: string) => {
  return customInstance<void>({ url: `/api/collections/${id}`, method: 'DELETE' });
};

export const getDeleteCollectionMutationOptions = <TError = Error[], TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteCollection>>, TError, { id: string }, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteCollection>>, TError, { id: string }, TContext> => {
  const mutationKey = ['deleteCollection'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCollection>>, { id: string }> = (props) => {
    const { id } = props ?? {};

    return deleteCollection(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCollectionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCollection>>>;

export type DeleteCollectionMutationError = Error[];

export const useDeleteCollection = <TError = Error[], TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteCollection>>, TError, { id: string }, TContext>;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof deleteCollection>>, TError, { id: string }, TContext> => {
  const mutationOptions = getDeleteCollectionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
