/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Snippet.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../axios-instance';
import type { EnumValueDto, Error } from '../models';

/**
 * @summary Retrieves values for the ProgrammingLanguage enum
 */
export const getProgrammingLanguageEnumValues = (signal?: AbortSignal) => {
  return customInstance<EnumValueDto[]>({ url: `/api/lookup/enums/programming-languages`, method: 'GET', signal });
};

export const getGetProgrammingLanguageEnumValuesQueryKey = () => {
  return [`/api/lookup/enums/programming-languages`] as const;
};

export const getGetProgrammingLanguageEnumValuesQueryOptions = <
  TData = Awaited<ReturnType<typeof getProgrammingLanguageEnumValues>>,
  TError = Error[]
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammingLanguageEnumValues>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProgrammingLanguageEnumValuesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProgrammingLanguageEnumValues>>> = ({ signal }) =>
    getProgrammingLanguageEnumValues(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProgrammingLanguageEnumValues>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProgrammingLanguageEnumValuesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProgrammingLanguageEnumValues>>
>;
export type GetProgrammingLanguageEnumValuesQueryError = Error[];

export function useGetProgrammingLanguageEnumValues<
  TData = Awaited<ReturnType<typeof getProgrammingLanguageEnumValues>>,
  TError = Error[]
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammingLanguageEnumValues>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProgrammingLanguageEnumValues>>,
          TError,
          Awaited<ReturnType<typeof getProgrammingLanguageEnumValues>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetProgrammingLanguageEnumValues<
  TData = Awaited<ReturnType<typeof getProgrammingLanguageEnumValues>>,
  TError = Error[]
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammingLanguageEnumValues>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProgrammingLanguageEnumValues>>,
          TError,
          Awaited<ReturnType<typeof getProgrammingLanguageEnumValues>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetProgrammingLanguageEnumValues<
  TData = Awaited<ReturnType<typeof getProgrammingLanguageEnumValues>>,
  TError = Error[]
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammingLanguageEnumValues>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Retrieves values for the ProgrammingLanguage enum
 */

export function useGetProgrammingLanguageEnumValues<
  TData = Awaited<ReturnType<typeof getProgrammingLanguageEnumValues>>,
  TError = Error[]
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammingLanguageEnumValues>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetProgrammingLanguageEnumValuesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
