/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Snippet.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddTagCommand,
  ChangeSnippetLanguageCommand,
  CreateSnippetCommand,
  Error,
  GetRecentSnippetsParams,
  GetSnippetByIdDto,
  MoveSnippetCommand,
  SearchSnippetsQuery,
  SearchSnippetsResponse,
  SnippetSummaryDto,
  UpdateSnippetContentCommand
} from '../models';

import { customInstance } from '../axios-instance';





export const createSnippet = (
    createSnippetCommand: CreateSnippetCommand,
 signal?: AbortSignal
) => {
      
      
      return customInstance<string>(
      {url: `/api/snippets`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSnippetCommand, signal
    },
      );
    }
  


export const getCreateSnippetMutationOptions = <TError = Error[],
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSnippet>>, TError,{data: CreateSnippetCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createSnippet>>, TError,{data: CreateSnippetCommand}, TContext> => {

const mutationKey = ['createSnippet'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSnippet>>, {data: CreateSnippetCommand}> = (props) => {
          const {data} = props ?? {};

          return  createSnippet(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateSnippetMutationResult = NonNullable<Awaited<ReturnType<typeof createSnippet>>>
    export type CreateSnippetMutationBody = CreateSnippetCommand
    export type CreateSnippetMutationError = Error[]

    export const useCreateSnippet = <TError = Error[],
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSnippet>>, TError,{data: CreateSnippetCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSnippet>>,
        TError,
        {data: CreateSnippetCommand},
        TContext
      > => {

      const mutationOptions = getCreateSnippetMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getUserSnippets = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<SnippetSummaryDto[]>(
      {url: `/api/snippets`, method: 'GET', signal
    },
      );
    }
  



export const getGetUserSnippetsQueryKey = () => {
    return [
    `/api/snippets`
    ] as const;
    }

    
export const getGetUserSnippetsQueryOptions = <TData = Awaited<ReturnType<typeof getUserSnippets>>, TError = Error[]>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSnippets>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserSnippetsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserSnippets>>> = ({ signal }) => getUserSnippets(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserSnippets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserSnippetsQueryResult = NonNullable<Awaited<ReturnType<typeof getUserSnippets>>>
export type GetUserSnippetsQueryError = Error[]


export function useGetUserSnippets<TData = Awaited<ReturnType<typeof getUserSnippets>>, TError = Error[]>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSnippets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserSnippets>>,
          TError,
          Awaited<ReturnType<typeof getUserSnippets>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserSnippets<TData = Awaited<ReturnType<typeof getUserSnippets>>, TError = Error[]>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSnippets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserSnippets>>,
          TError,
          Awaited<ReturnType<typeof getUserSnippets>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserSnippets<TData = Awaited<ReturnType<typeof getUserSnippets>>, TError = Error[]>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSnippets>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserSnippets<TData = Awaited<ReturnType<typeof getUserSnippets>>, TError = Error[]>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSnippets>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserSnippetsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateSnippetContent = (
    id: string,
    updateSnippetContentCommand: UpdateSnippetContentCommand,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/snippets/${id}/content`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateSnippetContentCommand
    },
      );
    }
  


export const getUpdateSnippetContentMutationOptions = <TError = Error[],
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSnippetContent>>, TError,{id: string;data: UpdateSnippetContentCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateSnippetContent>>, TError,{id: string;data: UpdateSnippetContentCommand}, TContext> => {

const mutationKey = ['updateSnippetContent'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSnippetContent>>, {id: string;data: UpdateSnippetContentCommand}> = (props) => {
          const {id,data} = props ?? {};

          return  updateSnippetContent(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateSnippetContentMutationResult = NonNullable<Awaited<ReturnType<typeof updateSnippetContent>>>
    export type UpdateSnippetContentMutationBody = UpdateSnippetContentCommand
    export type UpdateSnippetContentMutationError = Error[]

    export const useUpdateSnippetContent = <TError = Error[],
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSnippetContent>>, TError,{id: string;data: UpdateSnippetContentCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSnippetContent>>,
        TError,
        {id: string;data: UpdateSnippetContentCommand},
        TContext
      > => {

      const mutationOptions = getUpdateSnippetContentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const changeSnippetLanguage = (
    id: string,
    changeSnippetLanguageCommand: ChangeSnippetLanguageCommand,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/snippets/${id}/language`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: changeSnippetLanguageCommand
    },
      );
    }
  


export const getChangeSnippetLanguageMutationOptions = <TError = Error[],
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeSnippetLanguage>>, TError,{id: string;data: ChangeSnippetLanguageCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof changeSnippetLanguage>>, TError,{id: string;data: ChangeSnippetLanguageCommand}, TContext> => {

const mutationKey = ['changeSnippetLanguage'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changeSnippetLanguage>>, {id: string;data: ChangeSnippetLanguageCommand}> = (props) => {
          const {id,data} = props ?? {};

          return  changeSnippetLanguage(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChangeSnippetLanguageMutationResult = NonNullable<Awaited<ReturnType<typeof changeSnippetLanguage>>>
    export type ChangeSnippetLanguageMutationBody = ChangeSnippetLanguageCommand
    export type ChangeSnippetLanguageMutationError = Error[]

    export const useChangeSnippetLanguage = <TError = Error[],
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeSnippetLanguage>>, TError,{id: string;data: ChangeSnippetLanguageCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changeSnippetLanguage>>,
        TError,
        {id: string;data: ChangeSnippetLanguageCommand},
        TContext
      > => {

      const mutationOptions = getChangeSnippetLanguageMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const addTag = (
    id: string,
    addTagCommand: AddTagCommand,
 signal?: AbortSignal
) => {
      
      
      return customInstance<string>(
      {url: `/api/snippets/${id}/tags`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addTagCommand, signal
    },
      );
    }
  


export const getAddTagMutationOptions = <TError = Error[],
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addTag>>, TError,{id: string;data: AddTagCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof addTag>>, TError,{id: string;data: AddTagCommand}, TContext> => {

const mutationKey = ['addTag'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addTag>>, {id: string;data: AddTagCommand}> = (props) => {
          const {id,data} = props ?? {};

          return  addTag(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddTagMutationResult = NonNullable<Awaited<ReturnType<typeof addTag>>>
    export type AddTagMutationBody = AddTagCommand
    export type AddTagMutationError = Error[]

    export const useAddTag = <TError = Error[],
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addTag>>, TError,{id: string;data: AddTagCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addTag>>,
        TError,
        {id: string;data: AddTagCommand},
        TContext
      > => {

      const mutationOptions = getAddTagMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const removeTag = (
    id: string,
    tagId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/snippets/${id}/tags/${tagId}`, method: 'DELETE'
    },
      );
    }
  


export const getRemoveTagMutationOptions = <TError = Error[],
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeTag>>, TError,{id: string;tagId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof removeTag>>, TError,{id: string;tagId: string}, TContext> => {

const mutationKey = ['removeTag'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeTag>>, {id: string;tagId: string}> = (props) => {
          const {id,tagId} = props ?? {};

          return  removeTag(id,tagId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveTagMutationResult = NonNullable<Awaited<ReturnType<typeof removeTag>>>
    
    export type RemoveTagMutationError = Error[]

    export const useRemoveTag = <TError = Error[],
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeTag>>, TError,{id: string;tagId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeTag>>,
        TError,
        {id: string;tagId: string},
        TContext
      > => {

      const mutationOptions = getRemoveTagMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const toggleFavorite = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/snippets/${id}/favorite`, method: 'POST', signal
    },
      );
    }
  


export const getToggleFavoriteMutationOptions = <TError = Error[],
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleFavorite>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof toggleFavorite>>, TError,{id: string}, TContext> => {

const mutationKey = ['toggleFavorite'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toggleFavorite>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  toggleFavorite(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ToggleFavoriteMutationResult = NonNullable<Awaited<ReturnType<typeof toggleFavorite>>>
    
    export type ToggleFavoriteMutationError = Error[]

    export const useToggleFavorite = <TError = Error[],
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleFavorite>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof toggleFavorite>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getToggleFavoriteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const recordUsage = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/snippets/${id}/usage`, method: 'POST', signal
    },
      );
    }
  


export const getRecordUsageMutationOptions = <TError = Error[],
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof recordUsage>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof recordUsage>>, TError,{id: string}, TContext> => {

const mutationKey = ['recordUsage'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof recordUsage>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  recordUsage(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RecordUsageMutationResult = NonNullable<Awaited<ReturnType<typeof recordUsage>>>
    
    export type RecordUsageMutationError = Error[]

    export const useRecordUsage = <TError = Error[],
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof recordUsage>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof recordUsage>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getRecordUsageMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const moveSnippet = (
    id: string,
    moveSnippetCommand: MoveSnippetCommand,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/snippets/${id}/collections`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: moveSnippetCommand
    },
      );
    }
  


export const getMoveSnippetMutationOptions = <TError = Error[],
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moveSnippet>>, TError,{id: string;data: MoveSnippetCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof moveSnippet>>, TError,{id: string;data: MoveSnippetCommand}, TContext> => {

const mutationKey = ['moveSnippet'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof moveSnippet>>, {id: string;data: MoveSnippetCommand}> = (props) => {
          const {id,data} = props ?? {};

          return  moveSnippet(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MoveSnippetMutationResult = NonNullable<Awaited<ReturnType<typeof moveSnippet>>>
    export type MoveSnippetMutationBody = MoveSnippetCommand
    export type MoveSnippetMutationError = Error[]

    export const useMoveSnippet = <TError = Error[],
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moveSnippet>>, TError,{id: string;data: MoveSnippetCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof moveSnippet>>,
        TError,
        {id: string;data: MoveSnippetCommand},
        TContext
      > => {

      const mutationOptions = getMoveSnippetMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteSnippet = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/snippets/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteSnippetMutationOptions = <TError = Error[],
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSnippet>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteSnippet>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteSnippet'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSnippet>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteSnippet(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteSnippetMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSnippet>>>
    
    export type DeleteSnippetMutationError = Error[]

    export const useDeleteSnippet = <TError = Error[],
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSnippet>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSnippet>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteSnippetMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getSnippetById = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetSnippetByIdDto>(
      {url: `/api/snippets/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetSnippetByIdQueryKey = (id?: string,) => {
    return [
    `/api/snippets/${id}`
    ] as const;
    }

    
export const getGetSnippetByIdQueryOptions = <TData = Awaited<ReturnType<typeof getSnippetById>>, TError = Error[]>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSnippetById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSnippetByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSnippetById>>> = ({ signal }) => getSnippetById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSnippetById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSnippetByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getSnippetById>>>
export type GetSnippetByIdQueryError = Error[]


export function useGetSnippetById<TData = Awaited<ReturnType<typeof getSnippetById>>, TError = Error[]>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSnippetById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSnippetById>>,
          TError,
          Awaited<ReturnType<typeof getSnippetById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSnippetById<TData = Awaited<ReturnType<typeof getSnippetById>>, TError = Error[]>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSnippetById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSnippetById>>,
          TError,
          Awaited<ReturnType<typeof getSnippetById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSnippetById<TData = Awaited<ReturnType<typeof getSnippetById>>, TError = Error[]>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSnippetById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetSnippetById<TData = Awaited<ReturnType<typeof getSnippetById>>, TError = Error[]>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSnippetById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSnippetByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getCollectionSnippets = (
    collectionId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SnippetSummaryDto[]>(
      {url: `/api/snippets/collections/${collectionId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetCollectionSnippetsQueryKey = (collectionId?: string,) => {
    return [
    `/api/snippets/collections/${collectionId}`
    ] as const;
    }

    
export const getGetCollectionSnippetsQueryOptions = <TData = Awaited<ReturnType<typeof getCollectionSnippets>>, TError = Error[]>(collectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCollectionSnippets>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCollectionSnippetsQueryKey(collectionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCollectionSnippets>>> = ({ signal }) => getCollectionSnippets(collectionId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(collectionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCollectionSnippets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCollectionSnippetsQueryResult = NonNullable<Awaited<ReturnType<typeof getCollectionSnippets>>>
export type GetCollectionSnippetsQueryError = Error[]


export function useGetCollectionSnippets<TData = Awaited<ReturnType<typeof getCollectionSnippets>>, TError = Error[]>(
 collectionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCollectionSnippets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCollectionSnippets>>,
          TError,
          Awaited<ReturnType<typeof getCollectionSnippets>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCollectionSnippets<TData = Awaited<ReturnType<typeof getCollectionSnippets>>, TError = Error[]>(
 collectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCollectionSnippets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCollectionSnippets>>,
          TError,
          Awaited<ReturnType<typeof getCollectionSnippets>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCollectionSnippets<TData = Awaited<ReturnType<typeof getCollectionSnippets>>, TError = Error[]>(
 collectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCollectionSnippets>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCollectionSnippets<TData = Awaited<ReturnType<typeof getCollectionSnippets>>, TError = Error[]>(
 collectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCollectionSnippets>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCollectionSnippetsQueryOptions(collectionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getFavoriteSnippets = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<SnippetSummaryDto[]>(
      {url: `/api/snippets/favorites`, method: 'GET', signal
    },
      );
    }
  



export const getGetFavoriteSnippetsQueryKey = () => {
    return [
    `/api/snippets/favorites`
    ] as const;
    }

    
export const getGetFavoriteSnippetsQueryOptions = <TData = Awaited<ReturnType<typeof getFavoriteSnippets>>, TError = Error[]>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteSnippets>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFavoriteSnippetsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFavoriteSnippets>>> = ({ signal }) => getFavoriteSnippets(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFavoriteSnippets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFavoriteSnippetsQueryResult = NonNullable<Awaited<ReturnType<typeof getFavoriteSnippets>>>
export type GetFavoriteSnippetsQueryError = Error[]


export function useGetFavoriteSnippets<TData = Awaited<ReturnType<typeof getFavoriteSnippets>>, TError = Error[]>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteSnippets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFavoriteSnippets>>,
          TError,
          Awaited<ReturnType<typeof getFavoriteSnippets>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFavoriteSnippets<TData = Awaited<ReturnType<typeof getFavoriteSnippets>>, TError = Error[]>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteSnippets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFavoriteSnippets>>,
          TError,
          Awaited<ReturnType<typeof getFavoriteSnippets>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFavoriteSnippets<TData = Awaited<ReturnType<typeof getFavoriteSnippets>>, TError = Error[]>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteSnippets>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetFavoriteSnippets<TData = Awaited<ReturnType<typeof getFavoriteSnippets>>, TError = Error[]>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteSnippets>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFavoriteSnippetsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getRecentSnippets = (
    params: GetRecentSnippetsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SnippetSummaryDto[]>(
      {url: `/api/snippets/recent`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetRecentSnippetsQueryKey = (params?: GetRecentSnippetsParams,) => {
    return [
    `/api/snippets/recent`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetRecentSnippetsQueryOptions = <TData = Awaited<ReturnType<typeof getRecentSnippets>>, TError = Error[]>(params: GetRecentSnippetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentSnippets>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRecentSnippetsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecentSnippets>>> = ({ signal }) => getRecentSnippets(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRecentSnippets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRecentSnippetsQueryResult = NonNullable<Awaited<ReturnType<typeof getRecentSnippets>>>
export type GetRecentSnippetsQueryError = Error[]


export function useGetRecentSnippets<TData = Awaited<ReturnType<typeof getRecentSnippets>>, TError = Error[]>(
 params: GetRecentSnippetsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentSnippets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentSnippets>>,
          TError,
          Awaited<ReturnType<typeof getRecentSnippets>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecentSnippets<TData = Awaited<ReturnType<typeof getRecentSnippets>>, TError = Error[]>(
 params: GetRecentSnippetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentSnippets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentSnippets>>,
          TError,
          Awaited<ReturnType<typeof getRecentSnippets>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecentSnippets<TData = Awaited<ReturnType<typeof getRecentSnippets>>, TError = Error[]>(
 params: GetRecentSnippetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentSnippets>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetRecentSnippets<TData = Awaited<ReturnType<typeof getRecentSnippets>>, TError = Error[]>(
 params: GetRecentSnippetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentSnippets>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRecentSnippetsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const searchSnippets = (
    searchSnippetsQuery: SearchSnippetsQuery,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SearchSnippetsResponse>(
      {url: `/api/snippets/search`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: searchSnippetsQuery, signal
    },
      );
    }
  


export const getSearchSnippetsMutationOptions = <TError = Error[],
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof searchSnippets>>, TError,{data: SearchSnippetsQuery}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof searchSnippets>>, TError,{data: SearchSnippetsQuery}, TContext> => {

const mutationKey = ['searchSnippets'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof searchSnippets>>, {data: SearchSnippetsQuery}> = (props) => {
          const {data} = props ?? {};

          return  searchSnippets(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SearchSnippetsMutationResult = NonNullable<Awaited<ReturnType<typeof searchSnippets>>>
    export type SearchSnippetsMutationBody = SearchSnippetsQuery
    export type SearchSnippetsMutationError = Error[]

    export const useSearchSnippets = <TError = Error[],
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof searchSnippets>>, TError,{data: SearchSnippetsQuery}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof searchSnippets>>,
        TError,
        {data: SearchSnippetsQuery},
        TContext
      > => {

      const mutationOptions = getSearchSnippetsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    