/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Snippet.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../axios-instance';
import type { CreateTagCommand, Error, SearchTagsParams, TagDto2, TagSearchDto } from '../models';

export const searchTags = (params?: SearchTagsParams, signal?: AbortSignal) => {
  return customInstance<TagSearchDto[]>({ url: `/api/tags/search`, method: 'GET', params, signal });
};

export const getSearchTagsQueryKey = (params?: SearchTagsParams) => {
  return [`/api/tags/search`, ...(params ? [params] : [])] as const;
};

export const getSearchTagsQueryOptions = <TData = Awaited<ReturnType<typeof searchTags>>, TError = Error[]>(
  params?: SearchTagsParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData>> }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchTagsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchTags>>> = ({ signal }) => searchTags(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchTags>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchTagsQueryResult = NonNullable<Awaited<ReturnType<typeof searchTags>>>;
export type SearchTagsQueryError = Error[];

export function useSearchTags<TData = Awaited<ReturnType<typeof searchTags>>, TError = Error[]>(
  params: undefined | SearchTagsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchTags>>,
          TError,
          Awaited<ReturnType<typeof searchTags>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSearchTags<TData = Awaited<ReturnType<typeof searchTags>>, TError = Error[]>(
  params?: SearchTagsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchTags>>,
          TError,
          Awaited<ReturnType<typeof searchTags>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSearchTags<TData = Awaited<ReturnType<typeof searchTags>>, TError = Error[]>(
  params?: SearchTagsParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSearchTags<TData = Awaited<ReturnType<typeof searchTags>>, TError = Error[]>(
  params?: SearchTagsParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSearchTagsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getUserTags = (signal?: AbortSignal) => {
  return customInstance<TagDto2[]>({ url: `/api/tags`, method: 'GET', signal });
};

export const getGetUserTagsQueryKey = () => {
  return [`/api/tags`] as const;
};

export const getGetUserTagsQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserTags>>,
  TError = Error[]
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserTags>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserTagsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserTags>>> = ({ signal }) => getUserTags(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserTags>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserTagsQueryResult = NonNullable<Awaited<ReturnType<typeof getUserTags>>>;
export type GetUserTagsQueryError = Error[];

export function useGetUserTags<TData = Awaited<ReturnType<typeof getUserTags>>, TError = Error[]>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserTags>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserTags>>,
          TError,
          Awaited<ReturnType<typeof getUserTags>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserTags<TData = Awaited<ReturnType<typeof getUserTags>>, TError = Error[]>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserTags>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserTags>>,
          TError,
          Awaited<ReturnType<typeof getUserTags>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserTags<TData = Awaited<ReturnType<typeof getUserTags>>, TError = Error[]>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserTags>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetUserTags<TData = Awaited<ReturnType<typeof getUserTags>>, TError = Error[]>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserTags>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetUserTagsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createTag = (createTagCommand: CreateTagCommand, signal?: AbortSignal) => {
  return customInstance<string>({
    url: `/api/tags`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createTagCommand,
    signal
  });
};

export const getCreateTagMutationOptions = <TError = Error[], TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof createTag>>, TError, { data: CreateTagCommand }, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof createTag>>, TError, { data: CreateTagCommand }, TContext> => {
  const mutationKey = ['createTag'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTag>>, { data: CreateTagCommand }> = (props) => {
    const { data } = props ?? {};

    return createTag(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateTagMutationResult = NonNullable<Awaited<ReturnType<typeof createTag>>>;
export type CreateTagMutationBody = CreateTagCommand;
export type CreateTagMutationError = Error[];

export const useCreateTag = <TError = Error[], TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof createTag>>, TError, { data: CreateTagCommand }, TContext>;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof createTag>>, TError, { data: CreateTagCommand }, TContext> => {
  const mutationOptions = getCreateTagMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteTag = (id: string) => {
  return customInstance<void>({ url: `/api/tags/${id}`, method: 'DELETE' });
};

export const getDeleteTagMutationOptions = <TError = Error[], TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteTag>>, TError, { id: string }, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteTag>>, TError, { id: string }, TContext> => {
  const mutationKey = ['deleteTag'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTag>>, { id: string }> = (props) => {
    const { id } = props ?? {};

    return deleteTag(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteTagMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTag>>>;

export type DeleteTagMutationError = Error[];

export const useDeleteTag = <TError = Error[], TContext = unknown>(
  options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteTag>>, TError, { id: string }, TContext> },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof deleteTag>>, TError, { id: string }, TContext> => {
  const mutationOptions = getDeleteTagMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
