/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Snippet.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import { createMutation, createQuery } from '@tanstack/svelte-query';
import type {
	CreateMutationOptions,
	CreateMutationResult,
	CreateQueryOptions,
	CreateQueryResult,
	DataTag,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey
} from '@tanstack/svelte-query';

import type { CurrentUserDto, PermissionDto, ProblemDetails, Result, RoleDto } from '../models';

import { customInstance } from '../axios-instance';

/**
 * Get current authenticated user with roles and permissions
 */
export const getCurrentUser = (signal?: AbortSignal) => {
	return customInstance<CurrentUserDto>({ url: `/api/users/me`, method: 'GET', signal });
};

export const getGetCurrentUserQueryKey = () => {
	return [`/api/users/me`] as const;
};

export const getGetCurrentUserQueryOptions = <
	TData = Awaited<ReturnType<typeof getCurrentUser>>,
	TError = ProblemDetails
>(options?: {
	query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetCurrentUserQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({ signal }) => getCurrentUser(signal);

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof getCurrentUser>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCurrentUserQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>;
export type GetCurrentUserQueryError = ProblemDetails;

export function createGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = ProblemDetails>(
	options?: { query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> },
	queryClient?: QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetCurrentUserQueryOptions(options);

	const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Get all system roles with their permissions
 */
export const getAllRoles = (signal?: AbortSignal) => {
	return customInstance<RoleDto[]>({ url: `/api/users/roles`, method: 'GET', signal });
};

export const getGetAllRolesQueryKey = () => {
	return [`/api/users/roles`] as const;
};

export const getGetAllRolesQueryOptions = <
	TData = Awaited<ReturnType<typeof getAllRoles>>,
	TError = ProblemDetails
>(options?: {
	query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof getAllRoles>>, TError, TData>>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetAllRolesQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllRoles>>> = ({ signal }) => getAllRoles(signal);

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof getAllRoles>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllRolesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllRoles>>>;
export type GetAllRolesQueryError = ProblemDetails;

export function createGetAllRoles<TData = Awaited<ReturnType<typeof getAllRoles>>, TError = ProblemDetails>(
	options?: { query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof getAllRoles>>, TError, TData>> },
	queryClient?: QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetAllRolesQueryOptions(options);

	const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Get all system permissions grouped by module
 */
export const getAllPermissions = (signal?: AbortSignal) => {
	return customInstance<PermissionDto[]>({ url: `/api/users/permissions`, method: 'GET', signal });
};

export const getGetAllPermissionsQueryKey = () => {
	return [`/api/users/permissions`] as const;
};

export const getGetAllPermissionsQueryOptions = <
	TData = Awaited<ReturnType<typeof getAllPermissions>>,
	TError = ProblemDetails
>(options?: {
	query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof getAllPermissions>>, TError, TData>>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetAllPermissionsQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllPermissions>>> = ({ signal }) =>
		getAllPermissions(signal);

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof getAllPermissions>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllPermissionsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllPermissions>>>;
export type GetAllPermissionsQueryError = ProblemDetails;

export function createGetAllPermissions<TData = Awaited<ReturnType<typeof getAllPermissions>>, TError = ProblemDetails>(
	options?: { query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof getAllPermissions>>, TError, TData>> },
	queryClient?: QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetAllPermissionsQueryOptions(options);

	const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Assign a role to a user (requires user management permissions)
 */
export const assignRoleToUser = (userId: string, roleId: string, signal?: AbortSignal) => {
	return customInstance<Result>({ url: `/api/users/${userId}/roles/${roleId}`, method: 'POST', signal });
};

export const getAssignRoleToUserMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof assignRoleToUser>>,
		TError,
		{ userId: string; roleId: string },
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof assignRoleToUser>>,
	TError,
	{ userId: string; roleId: string },
	TContext
> => {
	const mutationKey = ['assignRoleToUser'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof assignRoleToUser>>,
		{ userId: string; roleId: string }
	> = (props) => {
		const { userId, roleId } = props ?? {};

		return assignRoleToUser(userId, roleId);
	};

	return { mutationFn, ...mutationOptions };
};

export type AssignRoleToUserMutationResult = NonNullable<Awaited<ReturnType<typeof assignRoleToUser>>>;

export type AssignRoleToUserMutationError = ProblemDetails;

export const createAssignRoleToUser = <TError = ProblemDetails, TContext = unknown>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof assignRoleToUser>>,
			TError,
			{ userId: string; roleId: string },
			TContext
		>;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof assignRoleToUser>>,
	TError,
	{ userId: string; roleId: string },
	TContext
> => {
	const mutationOptions = getAssignRoleToUserMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
/**
 * Remove a role from a user (requires user management permissions)
 */
export const removeRoleFromUser = (userId: string, roleId: string) => {
	return customInstance<Result>({ url: `/api/users/${userId}/roles/${roleId}`, method: 'DELETE' });
};

export const getRemoveRoleFromUserMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof removeRoleFromUser>>,
		TError,
		{ userId: string; roleId: string },
		TContext
	>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof removeRoleFromUser>>,
	TError,
	{ userId: string; roleId: string },
	TContext
> => {
	const mutationKey = ['removeRoleFromUser'];
	const { mutation: mutationOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof removeRoleFromUser>>,
		{ userId: string; roleId: string }
	> = (props) => {
		const { userId, roleId } = props ?? {};

		return removeRoleFromUser(userId, roleId);
	};

	return { mutationFn, ...mutationOptions };
};

export type RemoveRoleFromUserMutationResult = NonNullable<Awaited<ReturnType<typeof removeRoleFromUser>>>;

export type RemoveRoleFromUserMutationError = ProblemDetails;

export const createRemoveRoleFromUser = <TError = ProblemDetails, TContext = unknown>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof removeRoleFromUser>>,
			TError,
			{ userId: string; roleId: string },
			TContext
		>;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof removeRoleFromUser>>,
	TError,
	{ userId: string; roleId: string },
	TContext
> => {
	const mutationOptions = getRemoveRoleFromUserMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
