<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup Label="Local Module References">
    <ProjectReference Include="..\Snippet.Modules.Snippets.Application\Snippet.Modules.Snippets.Application.csproj" />
  </ItemGroup>

  <ItemGroup Label="BuildingBlocks References">
    <ProjectReference Include="..\..\..\BuildingBlocks\src\BuildingBlocks.Abstractions\BuildingBlocks.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\src\BuildingBlocks.Infrastructure\BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup Label="NuGet Package References">
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

</Project>
