<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup Label="Local Module References">
    <ProjectReference Include="..\Snippet.Modules.Snippets.Application\Snippet.Modules.Snippets.Application.csproj" />
  </ItemGroup>

  <ItemGroup Label="Shared References">
    <ProjectReference Include="..\..\..\Shared\Snippet.Shared\Snippet.Shared.csproj" />
  </ItemGroup>

  <ItemGroup Label="NuGet Package References">
    <PackageReference Include="Shared.Abstractions" />
    <PackageReference Include="Shared.Infrastructure" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

</Project>
