/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Snippet.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ProgrammingLanguage } from './programmingLanguage';

export interface ChangeSnippetLanguageCommand {
	id: string;
	language: ProgrammingLanguage;
}
