/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Snippet.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ProgrammingLanguage } from './programmingLanguage';

export interface CreateSnippetCommand {
  title: string;
  content: string;
  language: ProgrammingLanguage;
  /** @nullable */
  description: string | null;
  /** @nullable */
  collectionIds: string[] | null;
}
