/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Snippet.Web | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CurrentUserDto {
  id?: string;
  email?: string;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  pictureUrl?: string | null;
  isActive?: boolean;
  lastLoginAt?: string;
  roles?: string[];
  permissions?: string[];
}
