/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Snippet.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ProgrammingLanguage } from './programmingLanguage';
import type { CollectionSummaryDto } from './collectionSummaryDto';
import type { TagDto } from './tagDto';

export interface GetSnippetByIdDto {
	id: string;
	userId: string;
	title: string;
	/** @nullable */
	description: string | null;
	content: string;
	language: ProgrammingLanguage;
	collections: CollectionSummaryDto[];
	tags: TagDto[];
	isFavorite: boolean;
	usageCount: number;
	createdAt: string;
	/** @nullable */
	modifiedAt: string | null;
	/** @nullable */
	lastUsedAt: string | null;
}
