/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Snippet.Web | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ProblemDetails {
	/** @nullable */
	type?: string | null;
	/** @nullable */
	title?: string | null;
	/** @nullable */
	status?: number | null;
	/** @nullable */
	detail?: string | null;
	/** @nullable */
	instance?: string | null;
}
