/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Snippet.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ProgrammingLanguage } from './programmingLanguage';

export interface SearchSnippetsQuery {
	/** @nullable */
	searchTerm: string | null;
	/** @nullable */
	tags: string[] | null;
	/** @nullable */
	languages: ProgrammingLanguage[] | null;
	/** @nullable */
	favoritesOnly: boolean | null;
	/** @nullable */
	collectionId: string | null;
	pageNumber?: number;
	pageSize?: number;
}
