/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Snippet.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ProgrammingLanguage } from './programmingLanguage';
import type { CollectionSummaryDto } from './collectionSummaryDto';
import type { TagSummaryDto } from './tagSummaryDto';

export interface SnippetSummaryDto {
	id: string;
	title: string;
	language: ProgrammingLanguage;
	collections: CollectionSummaryDto[];
	tags: TagSummaryDto[];
	isFavorite: boolean;
	usageCount: number;
	createdAt: string;
	/** @nullable */
	lastUsedAt: string | null;
}
