/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Snippet.Web | v1
 * OpenAPI spec version: 1.0.0
 */

export interface TagDto2 {
  id: string;
  userId: string;
  name: string;
  /** @nullable */
  color: string | null;
  snippetCount: number;
  createdAt: string;
}
