/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Snippet.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ProgrammingLanguage } from './programmingLanguage';

export interface UpdateSnippetCommand {
  id: string;
  title: string;
  /** @nullable */
  description: string | null;
  content: string;
  language: ProgrammingLanguage;
  tagIds: string[];
  collectionIds: string[];
}
