<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup Label="Local Module References">
    <ProjectReference Include="..\Snippet.Modules.Snippets.Domain\Snippet.Modules.Snippets.Domain.csproj" />
  </ItemGroup>

  <ItemGroup Label="BuildingBlocks References">
    <ProjectReference Include="..\..\..\..\libs\BuildingBlocks\src\BuildingBlocks.Application\BuildingBlocks.Application.csproj" />
  </ItemGroup>

  <ItemGroup Label="Package References">
    <PackageReference Include="MediatR" />
  </ItemGroup>

</Project>
