<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup Label="Local Module References">
    <ProjectReference Include="..\Snippet.Modules.Snippets.Domain\Snippet.Modules.Snippets.Domain.csproj" />
  </ItemGroup>

  <ItemGroup Label="BuildingBlocks References">
    <ProjectReference Include="..\..\..\BuildingBlocks\src\BuildingBlocks.Abstractions\BuildingBlocks.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\src\BuildingBlocks.Infrastructure\BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup Label="NuGet Package References">
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

</Project>
