// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Snippet.Modules.Snippets.Infrastructure.Persistence;

#nullable disable

namespace Snippet.Modules.Snippets.Infrastructure.Migrations
{
    [DbContext(typeof(SnippetsDbContext))]
    [Migration("20251031184203_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Snippet.Modules.Snippets.Domain.Aggregates.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Collections_UserId");

                    b.HasIndex("UserId", "SortOrder")
                        .HasDatabaseName("IX_Collections_UserId_SortOrder");

                    b.ToTable("Collections", (string)null);
                });

            modelBuilder.Entity("Snippet.Modules.Snippets.Domain.Aggregates.Snippet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CollectionIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("CollectionIds");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Language")
                        .HasDatabaseName("IX_Snippets_Language");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Snippets_UserId");

                    b.HasIndex("UserId", "IsFavorite")
                        .HasDatabaseName("IX_Snippets_UserId_IsFavorite");

                    b.HasIndex("UserId", "LastUsedAt")
                        .HasDatabaseName("IX_Snippets_UserId_LastUsedAt");

                    b.ToTable("Snippets", (string)null);
                });

            modelBuilder.Entity("Snippet.Modules.Snippets.Domain.Aggregates.Snippet", b =>
                {
                    b.OwnsMany("Snippet.Modules.Snippets.Domain.Aggregates.Tag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("SnippetId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Color")
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("SnippetId", "Id");

                            b1.HasIndex("Name");

                            b1.ToTable("Tags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SnippetId");
                        });

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
