// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Snippet.Modules.Snippets.Infrastructure.Persistence;

#nullable disable

namespace Snippet.Modules.Snippets.Infrastructure.Migrations
{
    [DbContext(typeof(SnippetsDbContext))]
    [Migration("20251102062255_UseCompositeKeysForJoinTables")]
    partial class UseCompositeKeysForJoinTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Snippet.Modules.Snippets.Domain.Aggregates.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Collections_UserId");

                    b.HasIndex("UserId", "SortOrder")
                        .HasDatabaseName("IX_Collections_UserId_SortOrder");

                    b.ToTable("Collections", (string)null);
                });

            modelBuilder.Entity("Snippet.Modules.Snippets.Domain.Aggregates.Snippet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Language")
                        .HasDatabaseName("IX_Snippets_Language");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Snippets_UserId");

                    b.HasIndex("UserId", "IsFavorite")
                        .HasDatabaseName("IX_Snippets_UserId_IsFavorite");

                    b.HasIndex("UserId", "LastUsedAt")
                        .HasDatabaseName("IX_Snippets_UserId_LastUsedAt");

                    b.ToTable("Snippets", (string)null);
                });

            modelBuilder.Entity("Snippet.Modules.Snippets.Domain.Aggregates.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Tags_UserId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Tags_UserId_Name");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("Snippet.Modules.Snippets.Domain.Entities.SnippetCollection", b =>
                {
                    b.Property<Guid>("SnippetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.HasKey("SnippetId", "CollectionId");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("IX_SnippetCollections_CollectionId");

                    b.ToTable("SnippetCollections", (string)null);
                });

            modelBuilder.Entity("Snippet.Modules.Snippets.Domain.Entities.SnippetTag", b =>
                {
                    b.Property<Guid>("SnippetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("SnippetId", "TagId");

                    b.HasIndex("TagId")
                        .HasDatabaseName("IX_SnippetTags_TagId");

                    b.ToTable("SnippetTags", (string)null);
                });

            modelBuilder.Entity("Snippet.Modules.Snippets.Domain.Entities.SnippetCollection", b =>
                {
                    b.HasOne("Snippet.Modules.Snippets.Domain.Aggregates.Collection", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Snippet.Modules.Snippets.Domain.Aggregates.Snippet", "Snippet")
                        .WithMany("SnippetCollections")
                        .HasForeignKey("SnippetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Snippet");
                });

            modelBuilder.Entity("Snippet.Modules.Snippets.Domain.Entities.SnippetTag", b =>
                {
                    b.HasOne("Snippet.Modules.Snippets.Domain.Aggregates.Snippet", "Snippet")
                        .WithMany("SnippetTags")
                        .HasForeignKey("SnippetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Snippet.Modules.Snippets.Domain.Aggregates.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snippet");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Snippet.Modules.Snippets.Domain.Aggregates.Snippet", b =>
                {
                    b.Navigation("SnippetCollections");

                    b.Navigation("SnippetTags");
                });
#pragma warning restore 612, 618
        }
    }
}
